export const set = [
    {
        trial: 1,
        color: "blue",
        congruent: false,
        word: "red",
    },
    {
        trial: 2,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 3,
        color: "red",
        congruent: false,
        word: "green",
    },
    {
        trial: 4,
        color: "red",
        congruent: true,
        word: "blue",
    },
    {
        trial: 5,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 6,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 7,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 8,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 9,
        color: "red",
        congruent: false,
        word: "red",
    },
    {
        trial: 10,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 11,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 12,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 13,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 14,
        color: "blue",
        congruent: false,
        word: "red",
    },
    {
        trial: 15,
        color: "green",
        congruent: true,
        word: "green",
    },
];
