export const set = [
    {
        trial: 1,
        color: "blue",
        congruent: false,
        word: "red",
    },
    {
        trial: 2,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 3,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 4,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 5,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 6,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 7,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 8,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 9,
        color: "green",
        congruent: false,
        word: "blue",
    },
    {
        trial: 10,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 11,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 12,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 13,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 14,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 15,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 16,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 17,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 18,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 19,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 20,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 21,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 22,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 23,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 24,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 25,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 26,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 27,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 28,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 29,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 30,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 31,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 32,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 33,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 34,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 35,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 36,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 37,
        color: "red",
        congruent: false,
        word: "green",
    },
    {
        trial: 38,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 39,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 40,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 41,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 42,
        color: "green",
        congruent: false,
        word: "blue",
    },
    {
        trial: 43,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 44,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 45,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 46,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 47,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 48,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 49,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 50,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 51,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 52,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 53,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 54,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 55,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 56,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 57,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 58,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 59,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 60,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 61,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 62,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 63,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 64,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 65,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 66,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 67,
        color: "blue",
        congruent: false,
        word: "red",
    },
    {
        trial: 68,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 69,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 70,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 71,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 72,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 73,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 74,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 75,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 76,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 77,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 78,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 79,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 80,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 81,
        color: "green",
        congruent: false,
        word: "blue",
    },
    {
        trial: 82,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 83,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 84,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 85,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 86,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 87,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 88,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 89,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 90,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 91,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 92,
        color: "red",
        congruent: false,
        word: "green",
    },
    {
        trial: 93,
        color: "green",
        congruent: false,
        word: "blue",
    },
    {
        trial: 94,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 95,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 96,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 97,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 98,
        color: "blue",
        congruent: false,
        word: "green",
    },
    {
        trial: 99,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 100,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 101,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 102,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 103,
        color: "green",
        congruent: false,
        word: "red",
    },
    {
        trial: 104,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 105,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 106,
        color: "blue",
        congruent: false,
        word: "red",
    },
    {
        trial: 107,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 108,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 109,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 110,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 111,
        color: "red",
        congruent: false,
        word: "blue",
    },
    {
        trial: 112,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 113,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 114,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 115,
        color: "blue",
        congruent: false,
        word: "red",
    },
    {
        trial: 116,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 117,
        color: "blue",
        congruent: true,
        word: "blue",
    },
    {
        trial: 118,
        color: "red",
        congruent: true,
        word: "red",
    },
    {
        trial: 119,
        color: "green",
        congruent: true,
        word: "green",
    },
    {
        trial: 120,
        color: "blue",
        congruent: true,
        word: "blue",
    },
];
