import { FaceNameAssociationStimulus, FaceNameAssociationTaskTrialtype } from '../stimuli-models';

/**
 * We do not want face name manipulation to affect later trials so we turn
 * this into a function to ensure we are dealing with an array of new objects
 * every time
 */
export function getFaceNameAssociationStimuli(phase: 'learning-phase' | 'test-phase'): FaceNameAssociationStimulus[] {
    if (phase === 'learning-phase') {
        return [
            {
                personName: 'Mary',
                correctPersonName: 'Mary',
                imageName: '1F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Patricia',
                correctPersonName: 'Patricia',
                imageName: '2F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Jennifer',
                correctPersonName: 'Jennifer',
                imageName: '3F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Linda',
                correctPersonName: 'Linda',
                imageName: '4F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Elizabeth',
                correctPersonName: 'Elizabeth',
                imageName: '5F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Barbara',
                correctPersonName: 'Barbara',
                imageName: '6F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Susan',
                correctPersonName: 'Susan',
                imageName: '7F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Jessica',
                correctPersonName: 'Jessica',
                imageName: '8F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Sarah',
                correctPersonName: 'Sarah',
                imageName: '9F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Karen',
                correctPersonName: 'Karen',
                imageName: '10F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Nancy',
                correctPersonName: 'Nancy',
                imageName: '11F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Lisa',
                correctPersonName: 'Lisa',
                imageName: '12F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'James',
                correctPersonName: 'James',
                imageName: '1M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Robert',
                correctPersonName: 'Robert',
                imageName: '2M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'John',
                correctPersonName: 'John',
                imageName: '3M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Michael',
                correctPersonName: 'Michael',
                imageName: '4M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'William',
                correctPersonName: 'William',
                imageName: '5M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'David',
                correctPersonName: 'David',
                imageName: '6M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Richard',
                correctPersonName: 'Richard',
                imageName: '7M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Joseph',
                correctPersonName: 'Joseph',
                imageName: '8M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Thomas',
                correctPersonName: 'Thomas',
                imageName: '9M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Charles',
                correctPersonName: 'Charles',
                imageName: '10M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Christopher',
                correctPersonName: 'Christopher',
                imageName: '11M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Daniel',
                correctPersonName: 'Daniel',
                imageName: '12M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
        ];
    } else {
        return [
            {
                personName: 'Mary',
                correctPersonName: 'Mary',
                imageName: '1F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Patricia',
                correctPersonName: 'Patricia',
                imageName: '2F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Jennifer',
                correctPersonName: 'Jennifer',
                imageName: '3F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Linda',
                correctPersonName: 'Linda',
                imageName: '4F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Elizabeth',
                correctPersonName: 'Elizabeth',
                imageName: '5F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Barbara',
                correctPersonName: 'Barbara',
                imageName: '6F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Lisa',
                correctPersonName: 'Susan',
                imageName: '7F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Susan',
                correctPersonName: 'Jessica',
                imageName: '8F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Jessica',
                correctPersonName: 'Sarah',
                imageName: '9F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Sarah',
                correctPersonName: 'Karen',
                imageName: '10F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Karen',
                correctPersonName: 'Nancy',
                imageName: '11F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Nancy',
                correctPersonName: 'Lisa',
                imageName: '12F',
                isFemale: true,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'James',
                correctPersonName: 'James',
                imageName: '1M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Robert',
                correctPersonName: 'Robert',
                imageName: '2M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'John',
                correctPersonName: 'John',
                imageName: '3M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Michael',
                correctPersonName: 'Michael',
                imageName: '4M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'William',
                correctPersonName: 'William',
                imageName: '5M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'David',
                correctPersonName: 'David',
                imageName: '6M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.INTACT,
            },
            {
                personName: 'Daniel',
                correctPersonName: 'Richard',
                imageName: '7M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Richard',
                correctPersonName: 'Joseph',
                imageName: '8M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Joseph',
                correctPersonName: 'Thomas',
                imageName: '9M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Thomas',
                correctPersonName: 'Charles',
                imageName: '10M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Charles',
                correctPersonName: 'Christopher',
                imageName: '11M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
            {
                personName: 'Christopher',
                correctPersonName: 'Daniel',
                imageName: '12M',
                isFemale: false,
                trialType: FaceNameAssociationTaskTrialtype.RECOMBINED,
            },
        ];
    }
}
