export const RatingTaskActivities = {
    DoNothing: [
        'Rest',
        'Take a nap',
        'Daydream/stare out of the window',
        'Sit on the couch',
        'Do nothing in particular',
    ],
    DoSomething: [
        'Have a snack',
        'Watch street life from your window',
        'Listen to music',
        'Look up a medical condition',
        'Watch the news',
        'Watch a show or movie',
        'Read or listen to a book',
        'Play a game alone (e.g. on your phone)',
        'Browse the internet',
        'Tune into a radio show or podcast',
        'Chat with a neighbour',
        'Sort your mail',
        'Replace a lightbulb or other small fix-up',
        'Schedule an appointment',
        'Prepare a healthy snack',
        'Read up on a topic of interest',
        'Take a bath',
        'Order in food',
        'Pay your bills',
        'Take your medication',
        'Reply to emails',
        'Floss your teeth',
        'Prepare the grocery list',
        'Get gas for your car',
        'Go for a drive',
        'Play a game with others',
        'Write a thank you note',
        'Take the garbage out',
        'Make lunch',
        'Pick up something at the bakery',
        'Fill out an online survey',
        'Check your blood pressure',
        'Go get fast food',
        'Go for a walk outside',
        'Unload the dishwasher',
        'Go out for a meal at a new restaurant',
        'Write in a journal',
        'Go to the bank',
        'Go fill a prescription',
        'Organize your photos',
        'Go to the park',
        'Get the car washed',
        'Do the dishes',
        'Go to the liquor store',
        'Get a haircut',
        'Change your sheets',
        'Do a load of laundry',
        'Prepare a meal for someone',
        'Bake a treat',
        'Go shopping for clothes',
        'Organize your closet',
        'Go to the art gallery or museum',
        'Rake the leaves',
        'Organize your files',
        'Do the groceries',
        'Tidy the house',
        'Organize your cupboards',
        'Go to a cultural event',
        'Clean or vacuum the floor',
        'Organize financial documents for taxes',
        'Iron your dress clothes',
        'Go get blood tests',
        'Buy a birthday present for a friend or relative',
        'Clean the tub',
        'Garden or do yard work',
        'Attend an exercise class',
        'Attend a family gathering',
        'Go out with a friend',
        'Call up a friend/family',
        'Go to a sports game',
        'Take a class or workshop',
        'Respond to a text message',
        'Do some stretching',
    ],
};

// legend are ordered from low to high endorsement
export const RatingTaskQuestionList = [
    {
        question: 'How much do you look forward to the outcome of this activity?',
        legend: ['Not at all', 'Very much'],
    },
    {
        question: 'How much is this activity good for you?',
        legend: ['Not at all', 'Very good'],
    },
    {
        question: 'How much do you enjoy carrying out this activity?',
        legend: ['Not at all', 'Really enjoy'],
    },
    {
        question: 'How much do you feel you should do this activity?',
        legend: ["Really shouldn't", 'Really should'],
    },
    {
        question: 'How much do your loved ones think you should do this activity?',
        legend: ["Really shouldn't", 'Really should'],
    },
    {
        question: 'How physically effortful does this activity feel to you?',
        legend: ['Not at all', 'Very effortful'],
    },
    {
        question: 'How mentally effortful does this activity feel to you?',
        legend: ['Not at all', 'Very effortful'],
    },
    {
        question: 'How negative do you feel when doing this activity?',
        legend: ['Not at all', 'Very negative'],
    },
    {
        question: 'How hard is it to get started on this activity?',
        legend: ['Not at all', 'Very hard'],
    },
    {
        question: 'How much do you have to plan for this activity?',
        legend: ['None at all', 'Lots of planning'],
    },
    {
        question: 'To what extent is this activity part of your routine?',
        legend: ['Not at all', 'Very much'],
    },
    {
        question: 'How certain are you about how this activity will turn out?',
        legend: ['Not at all', 'Very certain'],
    },
    {
        question: 'How much does this activity help you feel close or connected to others?',
        legend: ['Not at all', 'Very much'],
    },
    {
        question: 'How much time does it usually take to do this activity?',
        legend: ['A few minutes', '30 minutes', 'Around an hour', 'A few hours', 'Most of the day'],
    },
    {
        question: 'How much money does it take to do this activity?',
        legend: ['Free', 'More than I can afford'],
    },
    {
        question: 'How often do you typically engage in this activity?',
        legend: ['A few times per lifetime or never', 'A few times per year', 'Monthly', 'Weekly', 'Daily'],
    },
    {
        question: 'How much does your age interfere with your ability to complete this activity?',
        legend: ['Not at all', 'A lot'],
    },
    {
        question: 'How much does your health condition affect your ability to complete this activity?',
        legend: ['Not at all', 'A lot'],
    },
];
