import { TrailMakingStimuliSet } from "../stimuli-models";

export const TrailMakingSet: TrailMakingStimuliSet = {
    numeric: {
        practice: {
            correctSequence: [1, 2, 3, 4, 5, 6, 7, 8],
            grid: [
                [
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: 2 },
                    { value: null },
                    { value: null },
                ],
                [
                    { value: 7 },
                    { value: null },
                    { value: 8 },
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: null },
                ],
                [
                    { value: null },
                    { value: null },
                    { value: 1 },
                    { value: null },
                    { value: 4 },
                    { value: null },
                    { value: 3 },
                ],
                [
                    { value: 6 },
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: 5 },
                    { value: null },
                    { value: null },
                ],
            ],
        },
        actual: {
            correctSequence: [
                1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
            ],
            grid: [
                [
                    { value: 15 },
                    { value: null },
                    { value: null },
                    { value: 17 },
                    { value: null },
                    { value: 11 },
                    { value: null },
                    { value: null },
                    { value: 21 },
                ],
                [
                    { value: null },
                    { value: 12 },
                    { value: null },
                    { value: 9 },
                    { value: null },
                    { value: 20 },
                    { value: null },
                    { value: 19 },
                    { value: null },
                ],
                [
                    { value: null },
                    { value: 16 },
                    { value: null },
                    { value: 2 },
                    { value: 18 },
                    { value: null },
                    { value: 25 },
                    { value: 3 },
                    { value: null },
                ],
                [
                    { value: 23 },
                    { value: null },
                    { value: 5 },
                    { value: null },
                    { value: null },
                    { value: 4 },
                    { value: null },
                    { value: null },
                    { value: 22 },
                ],
                [
                    { value: null },
                    { value: 13 },
                    { value: null },
                    { value: null },
                    { value: 6 },
                    { value: null },
                    { value: 8 },
                    { value: null },
                    { value: 10 },
                ],
                [
                    { value: 14 },
                    { value: 7 },
                    { value: null },
                    { value: null },
                    { value: 1 },
                    { value: null },
                    { value: null },
                    { value: 24 },
                    { value: null },
                ],
            ],
        },
    },
    alphanumeric: {
        practice: {
            correctSequence: [1, "A", 2, "B", 3, "C", 4, "D"],
            grid: [
                [
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: "A" },
                    { value: null },
                    { value: null },
                ],
                [
                    { value: 4 },
                    { value: null },
                    { value: "D" },
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: null },
                ],
                [
                    { value: null },
                    { value: null },
                    { value: 1 },
                    { value: null },
                    { value: "B" },
                    { value: null },
                    { value: 2 },
                ],
                [
                    { value: "C" },
                    { value: null },
                    { value: null },
                    { value: null },
                    { value: 3 },
                    { value: null },
                    { value: null },
                ],
            ],
        },
        actual: {
            correctSequence: [
                1,
                "A",
                2,
                "B",
                3,
                "C",
                4,
                "D",
                5,
                "E",
                6,
                "F",
                7,
                "G",
                8,
                "H",
                9,
                "I",
                10,
                "J",
                11,
                "K",
                12,
                "L",
                13,
            ],
            grid: [
                [
                    { value: 8 },
                    { value: null },
                    { value: null },
                    { value: 9 },
                    { value: null },
                    { value: 6 },
                    { value: null },
                    { value: null },
                    { value: 11 },
                ],
                [
                    { value: null },
                    { value: "F" },
                    { value: null },
                    { value: 5 },
                    { value: null },
                    { value: "J" },
                    { value: null },
                    { value: 10 },
                    { value: null },
                ],
                [
                    { value: null },
                    { value: "H" },
                    { value: null },
                    { value: "A" },
                    { value: "I" },
                    { value: null },
                    { value: 13 },
                    { value: 2 },
                    { value: null },
                ],
                [
                    { value: 12 },
                    { value: null },
                    { value: 3 },
                    { value: null },
                    { value: null },
                    { value: "B" },
                    { value: null },
                    { value: null },
                    { value: "K" },
                ],
                [
                    { value: null },
                    { value: 7 },
                    { value: null },
                    { value: null },
                    { value: "C" },
                    { value: null },
                    { value: "D" },
                    { value: null },
                    { value: "E" },
                ],
                [
                    { value: "G" },
                    { value: 4 },
                    { value: null },
                    { value: null },
                    { value: 1 },
                    { value: null },
                    { value: null },
                    { value: "L" },
                    { value: null },
                ],
            ],
        },
    },
};
