
export let activityList = [

    "Browse the internet",
    "Chat with a neighbour",
    "Check your blood pressure",
    "Choose a movie to watch",
    "Floss your teeth",
    "Go fill a prescription",
    "Go for a walk outside",
    "Go get fast food",
    "Go out for a meal at a new restaurant",
    "Go to the bank",
    "Go to the park",
    "Listen to music",
    "Look up a medical condition",
    "Make an appointment for the dentist",
    "Make lunch",
    "Order in food",
    "Organize your photos",
    "Pay your utilities bills",
    "Pick up pastries at the bakery",
    "Play a game alone",
    "Play a game with others",
    "Prepare the grocery list",
    "Read or listen to a book",
    "Read up on a topic of interest",
    "Register to vote",
    "Replace a lightbulb",
    "Reply to emails",
    "Reschedule a medical appointment",
    "Sort your mail",
    "Take a bath",
    "Take the garbage out",
    "Tune into a radio show or podcast",
    "Unpack your suitcase",
    "Watch the news",
    "Write a thank you note",
    "Write in a journal",
    "Clean the tub",
    "Do a load of laundry",
    "Do the dishes",
    "Get a haircut",
    "Go shopping for clothing",
    "Iron dress clothes",
    "Upgrade your computer or phone software",
    "Attend an exercise class at the gym",
    "Change your sheets", 
]